### ISSUE TITLE
'Exception' with message 'cannot create repository in non-existent directory'

### ISSUE THREAD

**Issue by algorys** [woolfg/dokuwiki-plugin-gitbacked#28]
Hello,

I've installed your plugin on my dokuwiki server, and I try to configure it. I've clone an existing repository and copy all data (with .git folder) to ./data/gitwiki. (I use gitwiki as the repos dir)

But when I edit a page I've only a blank page and no commit.

here is my log : 
```
[Tue Oct 06 15:35:43 2015] [error] [client 192.168.70.1] PHP Fatal error:  Uncaught exception 'Exception' with message 'cannot create repository in non-existent directory' in /var/www/alpi-wiki/lib/plugins/gitbacked/lib/Git.php:231\nStack trace:\n#0 /var/www/alpi-wiki/lib/plugins/gitbacked/lib/Git.php(180): GitRepo->set_repo_path('/var/www/alpi-w...', true, true)\n#1 /var/www/alpi-wiki/lib/plugins/gitbacked/action/editcommit.php(49): GitRepo->__construct('/var/www/alpi-w...', true, true)\n#2 /var/www/alpi-wiki/lib/plugins/gitbacked/action/editcommit.php(81): action_plugin_gitbacked_editcommit->initRepo()\n#3 /var/www/alpi-wiki/lib/plugins/gitbacked/action/editcommit.php(197): action_plugin_gitbacked_editcommit->commitFile('/var/www/alpi-w...', 'Wiki page accue...')\n#4 /var/www/alpi-wiki/inc/events.php(211): action_plugin_gitbacked_editcommit->handle_io_wikipage_write(Object(Doku_Event), NULL)\n#5 /var/www/alpi-wiki/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#6 /var/www/alpi-wiki/inc/events.php(115): Doku_Event->advise_after()\n#7 /var/www/alpi-wiki/i in /var/www/alpi-wiki/lib/plugins/gitbacked/lib/Git.php on line 231, referer: http://wiki.alpi-test.com/doku.php
```
It seems gitbacked don't find my repos and want to create one but I can't understand why ?

If you want more information, ask me.

Thanks in advance.

**Comment by woolfg** [comment]
what paths did you specify in the config section?

**Comment by algorys** [comment]
I had absolute paths before with an old version of your plugin in my old dokuwiki install.

So I make the same in this server but it seems not work.

Now, that's working with relative paths. Why ?

**Comment by algorys** [comment]
I've to precise that my repos is in [dokuwiki_root]/data/gitwiki and I set the following paths : 

```
./data/gitwiki
```

**Comment by algorys** [comment]
Ok,

That's solve for pushed, I've set url in http and not ssh :/ Sorry.

But I think, it'll be better if we can put absolute or relative path in conf.

**Comment by woolfg** [comment]
Afaik we always used relativ paths ;) - if you want to write a support for relative and absolute paths I would be very happy to accept your pull request (see #29)

**Comment by algorys** [comment]
Sorry I've to develop my own plugin before :) (I'm just amateur) but if I've some time, why not.

Thank you for the offer.
