### ISSUE TITLE
UTF-8 problem with git commit messages

### ISSUE THREAD

**Issue by ppoilbarbe** [woolfg/dokuwiki-plugin-gitbacked#30]
It seems that commit messages containing UTF-8 characters (such as accented chars) doe not work.
For exemple a message (message typed when saving or creating a page) like "Page créée" (french for "Page created") appears in git commit message as "Page cre" (all accented characters have been removed). It is true for any non ASCII characters I tried ("«»çéèàêâ")

**Comment by woolfg** [comment]
try to set the following setting somewhere in your php code, does it help?

```
setlocale(LC_CTYPE, "en_US.UTF-8");
´´´

**Comment by ppoilbarbe** [comment]
It works. I did not think about this since Apache is launched with all the environment variables set to en_US.UTF-8 (it may have been loosed somewhere).

**Comment by woolfg** [comment]
great that it works, it is needed for the shell execution and therefore, not set by default I think
