### ISSUE TITLE
gitbacked on an exisiting wiki repository

### ISSUE THREAD

**Issue by tuxillo** [woolfg/dokuwiki-plugin-gitbacked#33]
Hi,

I'm trying to use https://github.com/hoxu/dokuwiki2git.git to migrate the revisions of an already running wiki. But it turns out that on the first commit all exisiting pages are removed and the page modified for the change is shown as "modified" in git status.

Not sure if I'm missing something.

Thanks,
Antonio Huete

**Comment by woolfg** [comment]
have you done a manual rebase first? maybe that would help

**Comment by tuxillo** [comment]
Hi,

Rebase to what? There are two problems here:

1) If you use the program to convert the dokuwiki history to git repo it will do it correctly. Then, upon the first change your plugin removes EVERYTHING that is not the change you did in the wiki document.

2) The plugin leaves files modified when it should not. In my opinion it should leave the repository clean on every action and that's not happening. It is very easy to reproduce, just do what I described and you'll see it.

Cheers,
Antonio Huete

**Comment by woolfg** [comment]
I have never used dokuwiki2git.git, as it uses another approach it seems that the two plugins are not compatible. In general the plugin is just using the command line and add files to the git. If you find a fix, please, send a pull request.
