### ISSUE TITLE
Ability to add text commit

### ISSUE THREAD

**Issue by lex111** [woolfg/dokuwiki-plugin-gitbacked#37]
Ever wondered if over the fact that you can set your text commit? For example, the edit page of the page to add a field to enter a commit, commit if the text has been set, use it as a commit, and if not, then use a standard text commit. This is a useful opportunity in my opinion, because It lets make history meaningful commit.

**Comment by woolfg** [comment]
the placeholder %summary% (defined in the commit msg in the config) is replaced by the edit summary that can be specified when saving an edit.
