### ISSUE TITLE
Exception on empty commits (via Media Manager)

### ISSUE THREAD

**Issue by pgschk** [woolfg/dokuwiki-plugin-gitbacked#39]
Hi,

I ran into a problem when re-uploading files to the Media-Manager if they did not change.
For example: We have a process, in which a file is uploaded and overwritten weekly, however the file does not have to differ from the file uploaded the week before.

This triggers git to to state that there is nothing to be commited, as the file did not change from git's point of view. The problem with this is, that git returns exit state 1 and hence triggers line 317 in Git.php:

`if ($status) throw new Exception($stderr);
`

$stderr however is empty. The result is a white page for the http call, and this exception:

>  [client x.x.x.x:28525] PHP Fatal error:  Uncaught Exception in /var/www/dokuwiki/lib/plugins/gitbacked/lib/Git.php:317\nStack trace:\n#0 /var/www/dokuwiki/lib/plugins/gitbacked/lib/Git.php(332): GitRepo->run_command('/usr/bin/git --...')\n#1 /var/www/dokuwiki/lib/plugins/gitbacked/lib/Git.php(398): GitRepo->run('commit -av -m '...')\n#2 /var/www/dokuwiki/lib/plugins/gitbacked/action/editcommit.php(85): GitRepo->commit('Wiki media xxxx...')\n#3 /var/www/dokuwiki/lib/plugins/gitbacked/action/editcommit.php(154): action_plugin_gitbacked_editcommit->commitFile('/var/www/dokuwi...', 'Wiki media xxx...')\n#4 /var/www/dokuwiki/inc/events.php(211): action_plugin_gitbacked_editcommit->handle_media_upload(Object(Doku_Event), NULL)\n#5 /var/www/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#6 /var/www/dokuwiki/inc/events.php(115): Doku_Event->advise_after()\n#7 /var/www/dokuwiki/inc/events.php(238): Doku_Event->trigger('_media_upload_a...', true)\n#8 /var/www/dokuwiki/inc/media.php(464): trigger_event('MEDIA_UPLOAD_FI...', in /var/www/dokuwiki/lib/plugins/gitbacked/lib/Git.php on line 317, referer: https://xxx/doku.php?id=start&do=media&ns=

Three possible fixes for this is see are:
1.)  not trying to commit files that did not change 
2.) checking stdout in case of a set $status and ignore the problem if it is just an empty commit
3.) allow empty commits

I have patched Git.php for me to allow empty commits (Line 398):
`return $this->run("commit --allow-empty ".$flags." -m ".escapeshellarg($message));
`

This works for me, however I would avoid for future updates of the plugin to break this for me again, and I can imagine that you find a nicer way to solve this issue.

Thanks for your work!

**Comment by webhamster** [comment]
The same exception on empty commits occurs when using the struct plugin to associate metadata with a page and only changing this metadata. I think the --allow-empty should be adopted.

**Comment by woolfg** [comment]
I think your third solution is ok as you can also track every change even if there was no git related update
