### ISSUE TITLE
Changed page overwrites entire repo

### ISSUE THREAD

**Issue by brainthee** [woolfg/dokuwiki-plugin-gitbacked#40]
From a fresh install (fresh dokuwiki & installing gitbacked from the plugins tab) using the default configuration; when a page changes, only that page is pushed to the repo. This however overwrites everything else in the repo. The real actual working directory on the web server is still fine (so a quick add -A, commit and push fixes it).

Before commit:
![image](https://cloud.githubusercontent.com/assets/149447/18910360/89ae269c-856f-11e6-8627-b93d1d606fa7.png)

After saving the page:
![image](https://cloud.githubusercontent.com/assets/149447/18910368/90f60852-856f-11e6-8928-49cfd8cc7f4f.png)

I had to get this working ASAP so I've gone back to an old commit. e7471cfa47572f8fd7ae586ca257502473c36dc1 doesn't seem affected so I'm running with that at the moment. Would be good to get to the bottom of this though :)

**Comment by Doomas** [comment]
Hi,
i had the same issue. 

First to the solution. You have to set `repoPath` and `repoWorkDir` to the same Path (eg. `./data/gitrepo`) and not as described  in the [Documentation](https://www.dokuwiki.org/plugin:gitbacked) to different paths.

So, why is this. After a quick look at the code I found following lines:

[action/editcommit.php#L52](https://github.com/woolfg/dokuwiki-plugin-gitbacked/blob/d681a1859861ca2e683396c27c5f53f043701221/action/editcommit.php#L52)

```php
//set git working directory (by default DokuWiki's savedir)
$repoWorkDir = DOKU_INC.$this->getConf('repoWorkDir');
Git::set_bin(Git::get_bin().' --work-tree '.escapeshellarg($repoWorkDir));
```

So if you set the the configuration `repoWorkDir` to `./data/gitrepo/wiki`. It will move the root of your git Repo to `wiki`.

Im not sure what the reason behind this configuration option(`repoWorkDir`) is. And in my opinion this configuration option makes no sens, and should be removed. Or is there a real  use case for this?

**Comment by brainthee** [comment]
So I believe it's done that way so you can use the repo for other things. I.e. I have one repo for my wiki notes, scripts and tools.

That was one of the intended purposes I gathered from the documentation and makes it a very flexible setup.

Perhaps more importantly though, it used to work and since has been broken :)

@woolfg - any thoughts?

**Comment by Doomas** [comment]
Are you sure it worked? 

For me to use the git '--work-tree' option seems very strange. I never used it and i also never came across someone who did.

If you start with a Repository with multiple base directories( wiki, tools, script, etc. ) like in your example, you don't want move your working tree to 'wiki'.  It will produce exactly the problem you had here.
And if you start with an empty repo and you don't want a 'wiki' directory simply don't create it, instead create 'pages' and 'media' in your git root directory.

I don't think this option ads a lot of flexibility. I dare to say it makes the setup more confusing. 

However the major problem is the plugin documentation of the 'repoWorkDir' option. It is not correct, and you simply don't need this option in a normal setup.

**Comment by woolfg** [comment]
@brainthee is right, that was the main idea behind it. e.g. for software development sometimes, you want the code and the documentation in the same repo. it worked for me as well but to be honest I have to check it again as I designed it several years ago ;)

**Comment by woolfg** [comment]
closed as not active for a long time
