### ISSUE TITLE
Permission for adding object to repository is reset for every page saving

### ISSUE THREAD

**Issue by Alex-Space** [woolfg/dokuwiki-plugin-gitbacked#41]
Hi! I set permissiom of project folder for 777:
![image](https://cloud.githubusercontent.com/assets/7780469/24136634/e900dcd6-0e39-11e7-92fb-c8e8c3388d26.png)
When i saving a page in wiki:
![image](https://cloud.githubusercontent.com/assets/7780469/24136655/fdcb060a-0e39-11e7-81fd-d9f00a08239d.png)
When i trying to "git add ."  manualy:
![image](https://cloud.githubusercontent.com/assets/7780469/24136673/1647f80a-0e3a-11e7-8c9b-ae0240f03260.png)
And after that i set permission to 777 on project again and errors gone. But if i trying to save a page from wiki, it shows 500 error in browser and if i adding to git staging area manually i see theese error again:

error: insufficient permission for adding an object to repository database .git/objects
error: wiki/pages/start.txt: failed to insert into database
error: unable to index file wiki/pages/start.txt
fatal: adding files failed

What should i do to remove this permission problem?

**Comment by woolfg** [comment]
try to change the owner of the directory to your webserver user, e.g. chown apache:apache...

**Comment by woolfg** [comment]
closed as not active for a while. feel freee to reopen.
