### ISSUE TITLE
Setup Error - Gitrepo not accessible or writeable

### ISSUE THREAD

**Issue by 11ert** [woolfg/dokuwiki-plugin-gitbacked#46]
I do have some questions because I am not able to get the gitbacked plug-in up and running as expected:
I just followed the installation guidelines of the plug-in but I do get an error when opening my wiki pages:

`"The datadir ('pages') at ./data/gitrepo/wiki/pages is not found, isn't accessible or writable. You should check your config and permission settings. Or maybe you want to run the installer?"`

The corresponding configuration entry in local.php looks like:
```
$conf['plugin']['gitbacked']['pushAfterCommit'] = 1;
$conf['plugin']['gitbacked']['periodicPull'] = 1;
$conf['plugin']['gitbacked']['repoPath'] = './data/gitrepo';
$conf['plugin']['gitbacked']['repoWorkDir'] = './data/gitrepo/wiki';
$conf['plugin']['gitbacked']['addParams'] = '-c user.name="xyz" -c user.email="xxx@yyy.de"';
$conf['datadir'] = './data/gitrepo/wiki/pages';
$conf['mediadir'] = './data/gitrepo/wiki/media';
```
I executed a git pull within the folder (as my normal user). Dokuwiki could not access the files. So, I changed the ownership of the gitrepo folders to www-data but this does not help either:

```
pi@raspberrypi:/var/www/html/dokuwiki/data/gitrepo $ ls -lrt
insgesamt 8
drwxrwxr-x 3 www-data www-data 4096 Aug 16 22:59 wiki
```
Any ideas ? I would appreciate any help on this! Thanks in advance!

**Comment by Kirrito-k423** [comment]
I have the same question

**Comment by mhoffrog** [comment]
@Kirrito-k423 Please let us know the exact setup and config of your instance. There is a couple of confusion around `repoPath` and `repoWorkDir` config.

In most cases you just have to configure `repoPath` only and leave `repoWorkDir` empty!

Anyway - please let us know more details on your particular use case and on your actual configuration.
