### ISSUE TITLE
Errors while using with Publish plugin?

### ISSUE THREAD

**Issue by ghost** [woolfg/dokuwiki-plugin-gitbacked#5]
Hello,

I'm trying to set up a DokuWiki with both gitbacked and the publish plugin. I've noticed that when saving a document as "Approved" I get a git error. With publish disabled there is no problems. Any idea what could be happening here?

**Comment by valichek** [comment]
Hello, I got exception when enabled push after commit
push/pull work good from console, but not from dokuwiki

Fatal error: Uncaught exception 'Exception' with message 'fatal: '/home/git/repos/my-wiki.git' does not appear to be a git repository fatal: The remote end hung up unexpectedly ' in /home/user/www/.../wiki/lib/plugins/gitbacked/lib/Git.php:299 Stack trace: #0 /home/user/www/.../wiki/lib/plugins/gitbacked/lib/Git.php(314): GitRepo->run_command('/usr/bin/git pu...') #1 /home/user/www/.../wiki/lib/plugins/gitbacked/lib/Git.php(606): GitRepo->run('push --tags ori...') #2 /home/user/www/.../wiki/lib/plugins/gitbacked/action/editcommit.php(69): GitRepo->push('origin', 'master') #3 /home/user/www/.../wiki/lib/plugins/gitbacked/action/editcommit.php(176): action_plugin_gitbacked_editcommit->commitFile('/home/user/w...', 'Wiki page ?????...') #4 /home/.../www/.../wiki/inc/events.php(204): action_plugin_gitbacked_editcommit->handle_io_wikipage_write(Object(Doku_Event), NULL) #5 /home/.../www/.../wiki/inc/events.php(76): Doku_Event_Handler->process_eve in /home/user/www/.../wiki/lib/plugins/gitbacked/lib/Git.php on line 299

**Comment by valichek** [comment]
Got idea to set valid permissions for apache user and it fixed it.
