### ISSUE TITLE
media_attic not in git repo

### ISSUE THREAD

**Issue by bdynamic** [woolfg/dokuwiki-plugin-gitbacked#52]
Hi Wolfgang - first thanks for the great work - I love it!
Exploring my data directory (I installed the doku wiki in a docker) I realized that media_attic is not in the git repo. Anyhow this would be desirable because the draw.io plugin uses this directory for storage.

Unfortunately I could not figure out if there is a config option for media_atttic. Even the (obviously existing) config option $conf['mediadir'] is not mentioned here: https://www.dokuwiki.org/de:config

Could you give me a hint? Thanks and greetings from Munich
Birk

**Comment by woolfg** [comment]
Hey @bdynamic, thanks for the message. I am not familiar with the plugin. So if I understand you correctly `media_attic` is the directory and it is not in the repo path directory? Can you post how your directory structure looks like.

cheers, Wolfgang

**Comment by bdynamic** [comment]
Hey @woolfg - of course. This is the relevant part of the structure:

/data/zettelkasten/dokuwiki/data# tree -d -L 2
.
├── attic
│    ..... stuff deleted
├── gitrepo
│   ├── media
│   └── pages
├── media
│   └── wiki
├── media_attic
│   └── namespace subdir
├── media_meta
│    ..... stuff deleted
├── meta
│    ..... stuff deleted
└── pages
    └── wiki

My git controlled stuff is in gitrepo. The Plugin saves in media_attic.

Thanks and best regards
Birk

**Comment by woolfg** [comment]
@bdynamic have you tried to configure the plugin (if possible) to move the `media_attic` folder into `gitrepo`?

**Comment by bdynamic** [comment]
@Woolfg: Good Idea - I will habe a look in the source code and if not available yet do a enhancement suggestion / pull request. 
Thanks  a lot!
