### ISSUE TITLE
Send notification eMail in case of an error to a configurable mail address

### ISSUE THREAD

**Issue by mhoffrog** [woolfg/dokuwiki-plugin-gitbacked#53]
### Feature request:
I would like to configure an eMail address to receive a mail in case of git commands failing.
If this notification is configured, the current Exception / error message should not get to the end users web front end.

### Motivation:
IMO the current implementation is not very useful, since the end user editing pages will get irritated or confused, if a git command is failing in the background and this is shown as a more or less cryptic and raw error message in the users browser session. 
The current user cannot do anything to mitigate that situation. So it would make much more sense to get an admin user notified about such kind of gitbacked issues.

### Solution:
As I did implement this kind of extension I will create an appropriate pull request soon:

![image](https://user-images.githubusercontent.com/45703410/112554515-bbe01d00-8dc6-11eb-98f7-5f334bd11aba.png)

**Comment by woolfg** [comment]
Hey @mhoffrog, thanks a lot for the proposal and the PR. I will have a look asap. In general, is there maybe already a built-in error system in DW, which handles errors and might also send an email to the admin? To be honest, I was never the hard core DW developer, so I am not aware of the whole system but I think it is wise to follow the common rule of separation in architecture design: so collecting errors system wide -> handling errors by a error handler function -> config the error handler to send emails. What do you thing about? Cheers

**Comment by mhoffrog** [comment]
Hi @woolfg, thanks for putting attention to it! For sure, that kind of generic error handling would absolutely make sense but as far as I could see, there is nothing in yet. Maybe this is a topic for the DW forum. IMO such kind of generic error handling architecture would require to provide an appropriate interface for plugins or a convention for dedicated Exception class to be thrown, since I guess one would like to configure probably separate target eMail addresses per plugin or per error root or error category. It should be considered that there might different domain experts related to the exception root cause or error subject to be notified.
