### ISSUE TITLE
periodicPush - nice to have

### ISSUE THREAD

**Issue by fama** [woolfg/dokuwiki-plugin-gitbacked#59]
I have been using the extension for almost two years and it works so well.

I wish there was a config `periodicPush`.  The `pushAfterCommit` slows down the saving significantly (maybe 1-2 seconds for a save), while without `pushAfterCommit` is instantaneous. 

It would be nice to be able to configure the push once every certain period, so that a cron job to do the push were not needed (for the ones who do not up to the last second backup).

**Comment by woolfg** [comment]
I think it doesn't make sense to reimplement a "cron" in the plugin and it is also not that simple with php. you could just deactivate the `pushAfterCommit` and create a cron job that pushes git changes from time to time.

**Comment by woolfg** [comment]
feel free to reopen the issue in case you want something to add.
