### ISSUE TITLE
Compatibility with 2020-07-29 "Hogfather" 

### ISSUE THREAD

**Issue by vlp-git** [woolfg/dokuwiki-plugin-gitbacked#60]
Hello !

First, thanks for the plugins !

I have tried to install it with the last version of dokuwiki and unfortunately after the page refresh I have an error 500 issue. I have had to manually delete the plugin folder to restore my wiki.

Any tips ?

Thanks !

vlp

**Comment by woolfg** [comment]
hey @vlp-git, what PHP version do you use? maybe it is related to #57?

**Comment by woolfg** [comment]
closed as not active for a while. feel freee to reopen.
