### ISSUE TITLE
Use DokuWiki's user name & email address as commit author

### ISSUE THREAD

**Issue by mbunkus** [woolfg/dokuwiki-plugin-gitbacked#63]
I'm using the gitbackend plugin for improved history tracking & evaluation. I often find myself trying to determine who changed a certain line in a page, and git supports that nicely with `git annotate`. `git annotate` only shows the commit's revision, author & date by default, though, not the commit message. As the author isn't set forcibly during the commit, the author will always be the web server user (e.g. `www-data`).

I'd be nice for both `git annotate` and `git log` output to have the plugin set the user's name as the commit's author (`git commit --author "Moritz Bunkus" /path/to/filename`). That would make my life much easier.

Thanks for considering.

Edit: I initially wrote `git commit -a "Name <email>"`, which is wrong; `-a` is short for `--all`. The correct option is `--author`, for which there's no short name.

**Comment by mbunkus** [comment]
I actually hacked this in in our local installation by first changing `lib/Git.php`:

```php
    public function commit($message = "", $commit_all = true, $author = null, $email = null) {                                                                                                                                          
        $flags = $commit_all ? '-av' : '-v';                                                                                                                                                                                            
        $command = "commit " . $flags . " -m ".escapeshellarg($message);                                                                                                                                                                
        if ($author) {                                                                                                                                                                                                                  
            if ($email)                                                                                                                                                                                                                 
                $author .= " <" . $email . ">";                                                                                                                                                                                         
            $command .= " --author " . escapeshellarg($author);                                                                                                                                                                         
        }                                                                                                                                                                                                                               
        return $this->run($command);                                                                                                                                                                                                    
    }
```

and then `action/editcomment.php`, function `commitFile()`, to work like this (not the correct indentation):

```php
    $repo->commit($message, true, $this->getAuthor(), $this->getAuthorMail());
```

This seems to work for us after a very quick test, but there might be better ways to implement it.

**Comment by woolfg** [comment]
+1

**Comment by mhoffrog** [comment]
@ochurlaud, @mbunkus, @woolfg This feature request can already be achieved by appropriate configuration capabilities of this plugin without any new code change - see configuration description: https://github.com/woolfg/dokuwiki-plugin-gitbacked/blob/1edba4ef9408733fd8e1151f589a088debdec5ac/lang/en/settings.php#L19
Please make appropriate use of the configuration `$conf['addParams']` like e.g. `$conf['addParams'] = '-c user.name="%user%" -c user.email="%mail%"'`.
The placeholders `%user%` and `%mail%` are replaced by the DokuWiki managed login name and DokuWiki users eMail address.
This feature is implemented by the code at https://github.com/woolfg/dokuwiki-plugin-gitbacked/blob/1edba4ef9408733fd8e1151f589a088debdec5ac/action/editcommit.php#L54 to https://github.com/woolfg/dokuwiki-plugin-gitbacked/blob/1edba4ef9408733fd8e1151f589a088debdec5ac/action/editcommit.php#L60

**Comment by ochurlaud** [comment]
OK, then I'd propose to add it to the plug-in documentation and close the issue.

**Comment by mbunkus** [comment]
Thanks for the hint. Unfortunately this isn't at all that obvious. I'd even argue that the defaults should include those options: it strictly adds more information to use & alleviates the need for documentation.

Unfortunately adding the options unconditionally breaks if the user doesn't have an email address set if that is possible in MediaWiki. Another drawback of going the "arbitrary command line options" route is that no proper shell escaping is done.

So I understand you saying that having those options suffices, but it isn't actually a good solution in my opinion. It does suffice for my own use case, though, as we retrieve users from LDAP, and I know that a) each user does have an email address set and b) there are no characters needing further shell escaping in any of my users' names.
