### ISSUE TITLE
Move documentation from DokuWiki page to GitHub repo

### ISSUE THREAD

**Issue by woolfg** [woolfg/dokuwiki-plugin-gitbacked#67]
The documentation of the plugin is currently maintained at https://www.dokuwiki.org/plugin:gitbacked - As agreed with @mhoffrog, the documentation should be moved to the GitHub repo and a feature list should be added on the DokuWiki plugin page.

- [ ] Move documentation from https://www.dokuwiki.org/plugin:gitbacked into the README.md
- [ ] Create license file in repo to get rid of the license section in README.md
- [ ] Create feature list (and maybe also a better description) to promote plugin on https://www.dokuwiki.org/plugin:gitbacked

:green_heart: Contribution welcome: if you want to take over this issue, please, drop a message :green_heart:

**Comment by ochurlaud** [comment]
How are you going to update the dokuwiki.org/plugin page? Is there something automatic?
