### ISSUE TITLE
config param path of git bin

### ISSUE THREAD

**Issue by woolfg** [woolfg/dokuwiki-plugin-gitbacked#8]
Someone wrote: Note that this plugin only works if you have a git executable available at /usr/bin/git so it requires modifications to the Git wrapper script when you run a chrooted server or don't use linux. 

=> create a settings parameter to set the path of the git executable

**Comment by carstene1ns** [comment]
This one can be closed now. :+1:
Just needs some doc update here: https://www.dokuwiki.org/plugin:gitbacked

**Comment by woolfg** [comment]
feel free to edit the page....
