### ISSUE TITLE
Integration with plugins using the sqlite plugin

### ISSUE THREAD

**Issue by LonerDan** [woolfg/dokuwiki-plugin-gitbacked#88]
Hello,
Is there a way for this plugin to include a consistent snapshot of the SQLite file used by the dokuwiki's widespread SQLite plugin at the time of a commit?
Also, can it be made to work the other way around (ie trigger a commit when only the data in the database changes)?

**Comment by woolfg** [comment]
I am not familiar with the SQLite plugin but if there are hooks and with some glue code it could be possible. But I see it outside of the scope of the `dokuwiki-plugin-gitbacked` plugin. Maybe there are also changes needed in this plugin to provide some hooks for the glue code. Feel free to try to write a prototype and then we can see how we can make it work for other users. 

I will close this issue for now as I do not see it in the scope of the plugin but feel free to reopen it or open a new issue if you need any help.
