### ISSUE TITLE
Using Docker: Git committing or pushing failed: Host key verification failed. fatal: Could not read from remote repository. 

### ISSUE THREAD

**Issue by Kirrito-k423** [woolfg/dokuwiki-plugin-gitbacked#90]
## Problem

I have successfully configured the plugin following the step-by-step instructions provided in the official tutorial. However, when attempting to use the Gitbacked plugin within the [DokuWiki Docker container](https://github.com/Kirrito-k423/docker-dokuwiki), I encountered the following failure:

```
DokuWiki Setup Error: Something unforeseen has happened: Git committing or pushing failed: Host key verification failed. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
```

## My Confusion

Since I can run the plugin successfully outside of the Docker environment, I suspect the following might be the issue:

1. The `gitbacked plugin` utilizes the `www-data` user to perform the Git push.

If my assumption is correct, I have taken the following steps to resolve the issue:

- I added the SSH public key under `/var/www/.ssh` **within the Docker container terminal** to my GitHub account.
- I executed `chown -R www-data:www-data` on the `.ssh` and `.gitrepo` files.

However, I am unsure about how to test Git push using a `nologin` user.

I would appreciate any advice or insights to help resolve this issue. Thank you!

**Comment by mhoffrog** [comment]
@Kirrito-k423
If you are using ssh connection, you have to provide the ssh **private** key on the **git client system** - in your case this is your docker container hosting dokuwiki - and the **public** key must be provided to the **git remote host**.

An other - non ssh - option would be that you create a specific access token on the remote host to access your repo with read/writ access (e.g. GitLab or GitHub) and you configure the remote URL on your dokuwiki git repo config like `https://<user>:<access token>@github.com/<user>/<repo>.git`

**Comment by Kirrito-k423** [comment]
Utilizing a token for git push proves to be a straightforward and valuable solution. Thanks again.
